---
- hosts: default
  become: true
  become_user: root
  vars:
    virtualenv_path: ~vagrant/env
    workdir: ~vagrant/hostdir
  tasks:

# -------- update --------------------------------------------
  - name: update apt cache
    apt: update_cache=yes

# -------- environment ---------------------------------------
  - name: ensure OS environment
    apt: name={{packages}} state=present install_recommends=no
    vars:
      packages:
      - build-essential
      - python
      - python-setuptools
      - python-pip
      - python3
      - python3-setuptools
      - python3-venv
      - python3-pip
      - python3-dev
      - man-db
      - manpages
      - jq
      - chromium-driver
      - chromium
  - name: update pip
    pip: name=pip virtualenv={{ virtualenv_path }} virtualenv_command=pyvenv-3.5
    become: true
    become_user: vagrant

  - name: install Python packages
    pip: name={{packages}} virtualenv={{ virtualenv_path }} virtualenv_command=pyvenv-3.5
    vars:
      packages:
      - click
      - jsonschema
      - wheel
      - scrapy
      - selenium
      - ipython
      - beautifulsoup4
    become: true
    become_user: vagrant

# -------- shell ---------------------------------------------
  - name: .bashrc for vagrant user
    template: dest=~vagrant/.bashrc src=templates/etc/skel/.bashrc.j2 mode=0644 owner=vagrant group=vagrant
